### ISSUE TITLE
Thiết kế và lên danh sách các chức năng cần thiết - Chat App

### ISSUE THREAD

**Issue by vientamthuong** [vientamthuong/FrontEnd_ThayLong_Nhom-21#17]
**Nhóm đã họp vào chủ nhật - ngày 23  -5 - 2021 và thống nhất Chat App gồm 6 màn hình trước mắt (Có thể thêm ở tương lai): 
- Màn hình trang chủ
- Màn hình đăng nhập - đăng ký -quên mật khẩu 
- Màn hình danh sách bạn bè
- Màn hình chat
- Trang 404
- Màn hình cài đặt

**Với danh sách chức năng trước mắt (Có thể thêm ở tương lai):
- Đăng nhập
- Đăng ký
- Quên mật khẩu
- Kết bạn
- Xem thông tin bạn bè
- Quản lý thông tin bản thân
- Nhắn tin với bạn bè/ người lạ
- Cài đặt thông báo

** Thiết kế: Nhóm đã thông qua thiết kế tổng hợp tham khảo từ các nguồn và đã có hình dung chung về 2 màn hình trước mắt là màn hình chat và màn hình 404
- Màn hình chat
+ Tham khảo từ Messenger của facebook LINK: https://www.microsoft.com/en-us/p/messenger/9wzdncrf0083?activetab=pivot%3Aoverviewtab
+ Tham khảo từ Dribbble với các LINK:
    -->https://dribbble.com/shots/13869298-Chat-Interface-Web-Application
    -->https://dribbble.com/shots/14328055-Chat-Dashboard-UI
    -->https://dribbble.com/shots/5581652-All-Messaging-Media-in-One-Platform-Conceptual-Design
    -->https://dribbble.com/shots/11652535-Chat-dashboard-screen-design
    -->https://cdn.dribbble.com/users/1579320/screenshots/14723765/media/5d789d4028ba4ea9730004ce7e7ff7a4.mp4
- Màn hình 404
+ Tham khảo từ Dribbble với LINK: https://dribbble.com/shots/6711454-008-Daily-Ui-404-Page    

** Nhiệm vụ cho tất cả thành viên trong nhóm
1. Học Angular, cài đặt môi trường , cách làm việc nhóm với Angular + github để chuẩn bị cho tuần sau bắt đầu làm các component cho màn hình trang chủ và 404 Page

Thời hạn: Hết thứ 7 tuần sau (23:59  29-5-2021)

**Comment by 18130054** [comment]
Oke, viên cài đặt để chia nhỏ các component của trang chủ và tạo sẵn các pull request tương ứng cho tuần sau làm đi.

**Comment by 18130054** [comment]
File xd do nhóm tự thiết kế.
https://cdn.dribbble.com/users/1579320/screenshots/14723765/media/5d789d4028ba4ea9730004ce7e7ff7a4.mp4?fbclid=IwAR0INlYZciv3YtnbPoOHf4cTOUtEU6i4wQ2vl82B70ByI4HxnsWwV8iYPhg

**Comment by kieulinh2805** [comment]
https://drive.google.com/drive/folders/14i9ZcKroccIdTysdcJAj4KrVzhfwRTUS?usp=sharing
File thiết kế màn hình login để chuẩn bị cho tuần 3

**Comment by kieulinh2805** [comment]
https://drive.google.com/drive/folders/14i9ZcKroccIdTysdcJAj4KrVzhfwRTUS?usp=sharing
File thiết kế màn hình login để chuẩn bị cho tuần 3

**Comment by vientamthuong** [comment]
> Oke, viên cài đặt để chia nhỏ các component của trang chủ và tạo sẵn các pull request tương ứng cho tuần sau làm đi.

Oke nha

**Comment by vientamthuong** [comment]
Mọi người cố gắng học nhanh nhanh nha, tuần sau chúng ta bắt đầu làm rồi đấy !!!

**Comment by 18130054** [comment]
> Mọi người cố gắng học nhanh nhanh nha, tuần sau chúng ta bắt đầu làm rồi đấy !!!

OK Viên.

**Comment by kieulinh2805** [comment]
ok
